# Generated by Django 2.1 on 2019-03-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='request_details',
            field=models.TextField(default='Help me please', max_length=200),
            preserve_default=False,
        ),
    ]
