# Generated by Django 2.1.5 on 2019-03-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subscription',
            field=models.IntegerField(default=0),
        ),
    ]
