# Generated by Django 2.1.5 on 2019-03-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0003_assistanceapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='optionalDocument',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assist.Document'),
        ),
    ]
