# Generated by Django 2.1 on 2019-03-26 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0004_auto_20190324_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='optionalDocument',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assist.Document'),
        ),
    ]
