# Generated by Django 2.1.5 on 2019-05-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0005_auto_20190326_1221'),
        ('assist', '0007_auto_20190504_1340'),
    ]

    operations = [
    ]
