# Generated by Django 2.1.5 on 2019-05-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0008_merge_20190509_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='optionalDocument',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assist.Document'),
        ),
    ]
