# Generated by Django 2.1.5 on 2019-05-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0009_auto_20190509_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistanceapproval',
            name='is_approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
