# Generated by Django 2.1.5 on 2019-05-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0010_assistanceapproval_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assistanceapproval',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
