# Generated by Django 2.1.5 on 2019-05-28 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0011_auto_20190528_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancereview',
            name='text_rating',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistancereview',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
