# Generated by Django 2.1.5 on 2019-05-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0012_auto_20190528_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancereview',
            name='star_rating',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
