# Generated by Django 2.1.5 on 2019-05-31 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0014_auto_20190528_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistanceapproval',
            name='quote',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistanceapproval',
            name='repairer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assistanceapproval',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist.AssistanceRequest'),
        ),
    ]
